name: Deploy HTML

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      env:
        AWS_HOST: ${{ secrets.AWS_HOST }}
        AWS_USER: ${{ secrets.EC2_USER }}
        AWS_KEY: ${{ secrets.AWS_KEY }}
      run: |
        echo "Deploying application to EC2..."

        # Copy all HTML files to EC2
        scp -i $AWS_KEY -o StrictHostKeyChecking=no -r ./*.html ubuntu@$AWS_HOST:/var/www/html/

        # Connect to EC2 and restart NGINX
        ssh -i $AWS_KEY -o StrictHostKeyChecking=no ubuntu@$AWS_HOST << 'EOF'
          sudo systemctl restart nginx
          echo "Deployment completed!"
        EOF